a = input('1-sonni kiriting: ')
b = input('2-sonni kiriting: ')
print ('Kopaytmasi ', int(a)*int(b))
print ('Yegindisi ', int(a)+int(b))
print ('Kvadrati  ', int(a)*int(a))
print ('Kvadrati ', int(b)*int(b))